version: '3.1'

services:

  db:
    image: mysql:8.0.29
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 8081:3306
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 8080:8080