CREATE DATABASE IF NOT EXISTS budget_app_test;
USE budget_app_test;

DROP TABLE IF EXISTS articles;
DROP TABLE IF EXISTS receipts;
DROP TABLE IF EXISTS marketplaces;
DROP TABLE IF EXISTS currencies;
DROP TABLE IF EXISTS categories;

CREATE TABLE IF NOT EXISTS marketplaces(
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) NOT NULL, 
    address VARCHAR(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS currencies(
    code CHAR(3) UNIQUE NOT NULL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS categories(
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    icon_name VARCHAR(30) NOT NULL,
    color_main VARCHAR(7) NOT NULL,
    color_border VARCHAR(7) NOT NULL
);

CREATE TABLE IF NOT EXISTS receipts(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    marketplace_id SMALLINT UNSIGNED NOT NULL,
    receipt_date TIMESTAMP NOT NULL,
    total_price INT UNSIGNED NOT NULL,
    currency CHAR(3) NOT NULL,
    FOREIGN KEY(currency) REFERENCES currencies(code) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(marketplace_id) REFERENCES marketplaces(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS articles(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(60) NOT NULL,
    category_id SMALLINT UNSIGNED NOT NULL,
    receipt_id INT UNSIGNED NOT NULL,
    unit_price INT UNSIGNED NOT NULL,
    amount INT UNSIGNED NOT NULL DEFAULT 1,
    total_price INT UNSIGNED,
    currency CHAR(3) NOT NULL,
    FOREIGN KEY (category_id) REFERENCES categories(id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (receipt_id) REFERENCES receipts(id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (currency) REFERENCES currencies(code) ON UPDATE CASCADE ON DELETE CASCADE
);
